# Generated by Django 5.1.7 on 2025-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_alter_firsttimer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsttimer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
